### ISSUE TITLE
Qt 5.9.7 构建失败

### ISSUE THREAD

**Issue by GitHubAmos** [afterthat97/AshEngine#3]
**描述**
Qt 5.9.7 构建失败~~~

**错误信息：**
![1661754558375](https://user-images.githubusercontent.com/40637045/187137055-70197035-ebbf-4f3f-9e2a-47b12c925f78.png)
**isnan函数重载问题:**
![16617546942597](https://user-images.githubusercontent.com/40637045/187137486-a8d433bd-3aa4-42c1-8ede-5b8fee6b62d1.png)

**环境:**
 - OS: Windows 10 x64
 - MinGW: mingw53_32

**Comment by Tx-Charlie** [comment]
可以尝试下面的方式:
1. 替换内部链接的 assimp, 改为链接到本地即可
2. 添加头文件 `#include <math.h>` 解决
